##
## 'books' schema
##
#books:
#  lock_attributes: true
#  attributes:
#    - name: name
#      type: string
#    - name: isbn
#      type: string
#      unique: true
#    - name: genre
#      type: string
#
#  relationships:
#    belongs_to: authors
#
##
## 'authors' schema
##
#authors:
#  attributes:
#    - name: name
#      type: string
#
#  relationships:
#    has_many: books
